// react/src/ActorDetails.tsx
import { useQuery } from "@apollo/client/react"
import { useEffect } from "react"
import { useParams, useNavigate, Link } from "react-router-dom"
import { graphql } from "./gql"
import slugify from "./slugify"

const ACTOR = graphql(`
  query Actor($actorId: Int!) {
    actor(where: { id: { eq: $actorId } }) {
      id
      firstName
      lastName
      movies {
        id
        name
      }
    }
  }
`)

export default function ActorDetails() {
  const { actorId, name } = useParams<"actorId" | "name">()
  if (!actorId) throw new Error()

  const navigate = useNavigate()

  const { loading, error, data } = useQuery(ACTOR, {
    variables: { actorId: parseInt(actorId) },
  })

  // Redirect if missing url-name
  useEffect(() => {
    if (loading || error || !data || !data.actor) return

    if (!name)
      navigate(
        `/actor/${data.actor.id}/${slugify(
          `${data.actor.firstName} ${data.actor.lastName}`
        )}`
      )
  }, [loading, error, data, name, navigate])

  if (loading) return <p>LOADING...</p>
  if (error) return <p>Error: {JSON.stringify(error)}</p>
  if (!data || !data.actor) return <p>Error :(</p>

  return (
    <div>
      <button onClick={() => navigate("..")}>go back</button>
      <h1>
        {data.actor.firstName} {data.actor.lastName}
      </h1>
      <ul>
        {data.actor.movies.map((movie) => (
          <Link key={movie.id} to={`/movie/${movie.id}/${slugify(movie.name)}`}>
            <li>{movie.name}</li>
          </Link>
        ))}
      </ul>
    </div>
  )
}

// vue/src/ActorDetails.vue
<script setup lang="ts">
import { useQuery } from '@vue/apollo-composable'
import { graphql } from './gql'
import { useRoute, useRouter } from 'vue-router'
import slugify from './slugify'

const router = useRouter()
const route = useRoute()

const ACTOR = graphql(`
  query Actor($actorId: Int!) {
    actor(where: { id: { eq: $actorId } }) {
      id
      firstName
      lastName
      movies {
        id
        name
      }
    }
  }
`)

const id =
  typeof route.params.id === 'string'
    ? parseInt(route.params.id)
    : (() => {
        throw Error('Failed to get id')
      })()

const { loading, error, result } = useQuery(ACTOR, { actorId: id })
</script>

<template>
  <p v-if="loading">Loading...</p>
  <p v-else-if="error">{{ error }}</p>
  <div v-else>
    <button v-on:click="router.push('..')">go back</button>
    <h1>{{ result?.actor?.firstName }} {{ result?.actor?.lastName }}</h1>
    <ul>
      <template v-for="movie in result?.actor?.movies" :key="movie.id">
        <RouterLink :to="`/movie/${movie.id}/${slugify(movie.name)}`">
          <li>{{ movie.name }}</li>
        </RouterLink>
      </template>
    </ul>
  </div>
</template>
